INSERT INTO recipe_ingredients (recipe_id, ingredient_id, quantity, unit)
VALUES
  -- Breakfast
  ((SELECT id FROM recipes WHERE name = 'Peanut Butter Toast'), (SELECT id FROM ingredients WHERE name = 'Peanut Butter'), 30, 'g'),
  ((SELECT id FROM recipes WHERE name = 'Oatmeal with Banana'), (SELECT id FROM ingredients WHERE name = 'Oats'), 50, 'g'),
  ((SELECT id FROM recipes WHERE name = 'Oatmeal with Banana'), (SELECT id FROM ingredients WHERE name = 'Banana'), 1, 'piece'),
  ((SELECT id FROM recipes WHERE name = 'Greek Yogurt & Almonds'), (SELECT id FROM ingredients WHERE name = 'Greek Yogurt'), 100, 'g'),
  ((SELECT id FROM recipes WHERE name = 'Greek Yogurt & Almonds'), (SELECT id FROM ingredients WHERE name = 'Almonds'), 20, 'g'),
  ((SELECT id FROM recipes WHERE name = 'Tofu Scramble'), (SELECT id FROM ingredients WHERE name = 'Tofu'), 100, 'g'),
  ((SELECT id FROM recipes WHERE name = 'Tofu Scramble'), (SELECT id FROM ingredients WHERE name = 'Spinach'), 50, 'g'),
  ((SELECT id FROM recipes WHERE name = 'Tofu Scramble'), (SELECT id FROM ingredients WHERE name = 'Tomato'), 50, 'g'),
  ((SELECT id FROM recipes WHERE name = 'Egg & Spinach Wrap'), (SELECT id FROM ingredients WHERE name = 'Egg'), 1, 'piece'),
  ((SELECT id FROM recipes WHERE name = 'Egg & Spinach Wrap'), (SELECT id FROM ingredients WHERE name = 'Spinach'), 30, 'g'),
  ((SELECT id FROM recipes WHERE name = 'Egg & Spinach Wrap'), (SELECT id FROM ingredients WHERE name = 'Whole Wheat Bread'), 1, 'slice'),
  ((SELECT id FROM recipes WHERE name = 'Avocado Toast'), (SELECT id FROM ingredients WHERE name = 'Avocado'), 1, 'piece'),
  ((SELECT id FROM recipes WHERE name = 'Avocado Toast'), (SELECT id FROM ingredients WHERE name = 'Whole Wheat Bread'), 1, 'slice'),
  ((SELECT id FROM recipes WHERE name = 'Apple & Peanut Butter'), (SELECT id FROM ingredients WHERE name = 'Apple'), 1, 'piece'),
  ((SELECT id FROM recipes WHERE name = 'Apple & Peanut Butter'), (SELECT id FROM ingredients WHERE name = 'Peanut Butter'), 20, 'g'),
  -- Lunch
  ((SELECT id FROM recipes WHERE name = 'Grilled Chicken & Broccoli'), (SELECT id FROM ingredients WHERE name = 'Chicken Breast'), 150, 'g'),
  ((SELECT id FROM recipes WHERE name = 'Grilled Chicken & Broccoli'), (SELECT id FROM ingredients WHERE name = 'Broccoli'), 100, 'g'),
  ((SELECT id FROM recipes WHERE name = 'Egg Fried Rice'), (SELECT id FROM ingredients WHERE name = 'Egg'), 2, 'piece'),
  ((SELECT id FROM recipes WHERE name = 'Egg Fried Rice'), (SELECT id FROM ingredients WHERE name = 'Rice'), 100, 'g'),
  ((SELECT id FROM recipes WHERE name = 'Lentil Salad'), (SELECT id FROM ingredients WHERE name = 'Lentils'), 100, 'g'),
  ((SELECT id FROM recipes WHERE name = 'Lentil Salad'), (SELECT id FROM ingredients WHERE name = 'Tomato'), 50, 'g'),
  ((SELECT id FROM recipes WHERE name = 'Lentil Salad'), (SELECT id FROM ingredients WHERE name = 'Cucumber'), 50, 'g'),
  ((SELECT id FROM recipes WHERE name = 'Lentil Salad'), (SELECT id FROM ingredients WHERE name = 'Spinach'), 30, 'g'),
  ((SELECT id FROM recipes WHERE name = 'Chicken Avocado Wrap'), (SELECT id FROM ingredients WHERE name = 'Chicken Breast'), 100, 'g'),
  ((SELECT id FROM recipes WHERE name = 'Chicken Avocado Wrap'), (SELECT id FROM ingredients WHERE name = 'Avocado'), 1, 'piece'),
  ((SELECT id FROM recipes WHERE name = 'Chicken Avocado Wrap'), (SELECT id FROM ingredients WHERE name = 'Spinach'), 30, 'g'),
  ((SELECT id FROM recipes WHERE name = 'Chicken Avocado Wrap'), (SELECT id FROM ingredients WHERE name = 'Whole Wheat Bread'), 1, 'slice'),
  ((SELECT id FROM recipes WHERE name = 'Tofu & Broccoli Stir Fry'), (SELECT id FROM ingredients WHERE name = 'Tofu'), 100, 'g'),
  ((SELECT id FROM recipes WHERE name = 'Tofu & Broccoli Stir Fry'), (SELECT id FROM ingredients WHERE name = 'Broccoli'), 50, 'g'),
  ((SELECT id FROM recipes WHERE name = 'Chickpea Salad'), (SELECT id FROM ingredients WHERE name = 'Chickpeas'), 100, 'g'),
  ((SELECT id FROM recipes WHERE name = 'Chickpea Salad'), (SELECT id FROM ingredients WHERE name = 'Tomato'), 50, 'g'),
  ((SELECT id FROM recipes WHERE name = 'Chickpea Salad'), (SELECT id FROM ingredients WHERE name = 'Cucumber'), 50, 'g'),
  ((SELECT id FROM recipes WHERE name = 'Cheese & Tomato Sandwich'), (SELECT id FROM ingredients WHERE name = 'Cheddar Cheese'), 50, 'g'),
  ((SELECT id FROM recipes WHERE name = 'Cheese & Tomato Sandwich'), (SELECT id FROM ingredients WHERE name = 'Tomato'), 30, 'g'),
  ((SELECT id FROM recipes WHERE name = 'Cheese & Tomato Sandwich'), (SELECT id FROM ingredients WHERE name = 'Whole Wheat Bread'), 2, 'slice'),
  -- Dinner
  ((SELECT id FROM recipes WHERE name = 'Salmon Rice Bowl'), (SELECT id FROM ingredients WHERE name = 'Salmon'), 120, 'g'),
  ((SELECT id FROM recipes WHERE name = 'Salmon Rice Bowl'), (SELECT id FROM ingredients WHERE name = 'Rice'), 100, 'g'),
  ((SELECT id FROM recipes WHERE name = 'Chicken & Rice'), (SELECT id FROM ingredients WHERE name = 'Chicken Breast'), 120, 'g'),
  ((SELECT id FROM recipes WHERE name = 'Chicken & Rice'), (SELECT id FROM ingredients WHERE name = 'Rice'), 100, 'g'),
  ((SELECT id FROM recipes WHERE name = 'Tofu Curry'), (SELECT id FROM ingredients WHERE name = 'Tofu'), 100, 'g'),
  ((SELECT id FROM recipes WHERE name = 'Tofu Curry'), (SELECT id FROM ingredients WHERE name = 'Tomato'), 50, 'g'),
  ((SELECT id FROM recipes WHERE name = 'Tofu Curry'), (SELECT id FROM ingredients WHERE name = 'Spinach'), 30, 'g'),
  ((SELECT id FROM recipes WHERE name = 'Eggplant Lentil Stew'), (SELECT id FROM ingredients WHERE name = 'Lentils'), 100, 'g'),
  ((SELECT id FROM recipes WHERE name = 'Eggplant Lentil Stew'), (SELECT id FROM ingredients WHERE name = 'Spinach'), 30, 'g'),
  ((SELECT id FROM recipes WHERE name = 'Grilled Salmon & Spinach'), (SELECT id FROM ingredients WHERE name = 'Salmon'), 120, 'g'),
  ((SELECT id FROM recipes WHERE name = 'Grilled Salmon & Spinach'), (SELECT id FROM ingredients WHERE name = 'Spinach'), 30, 'g'),
  ((SELECT id FROM recipes WHERE name = 'Chickpea & Rice Pilaf'), (SELECT id FROM ingredients WHERE name = 'Chickpeas'), 100, 'g'),
  ((SELECT id FROM recipes WHERE name = 'Chickpea & Rice Pilaf'), (SELECT id FROM ingredients WHERE name = 'Rice'), 100, 'g'),
  ((SELECT id FROM recipes WHERE name = 'Vegetable Stir Fry'), (SELECT id FROM ingredients WHERE name = 'Broccoli'), 100, 'g'),
  ((SELECT id FROM recipes WHERE name = 'Vegetable Stir Fry'), (SELECT id FROM ingredients WHERE name = 'Tomato'), 50, 'g'),
  ((SELECT id FROM recipes WHERE name = 'Vegetable Stir Fry'), (SELECT id FROM ingredients WHERE name = 'Cucumber'), 50, 'g'),
  -- Snack
  ((SELECT id FROM recipes WHERE name = 'Greek Yogurt & Banana'), (SELECT id FROM ingredients WHERE name = 'Greek Yogurt'), 50, 'g'),
  ((SELECT id FROM recipes WHERE name = 'Greek Yogurt & Banana'), (SELECT id FROM ingredients WHERE name = 'Banana'), 1, 'piece'),
  ((SELECT id FROM recipes WHERE name = 'Almonds & Apple'), (SELECT id FROM ingredients WHERE name = 'Almonds'), 20, 'g'),
  ((SELECT id FROM recipes WHERE name = 'Almonds & Apple'), (SELECT id FROM ingredients WHERE name = 'Apple'), 1, 'piece'),
  ((SELECT id FROM recipes WHERE name = 'Peanut Butter Rice Cake'), (SELECT id FROM ingredients WHERE name = 'Peanut Butter'), 20, 'g'),
  ((SELECT id FROM recipes WHERE name = 'Peanut Butter Rice Cake'), (SELECT id FROM ingredients WHERE name = 'Rice'), 1, 'piece'),
  ((SELECT id FROM recipes WHERE name = 'Cucumber & Tomato Salad'), (SELECT id FROM ingredients WHERE name = 'Cucumber'), 50, 'g'),
  ((SELECT id FROM recipes WHERE name = 'Cucumber & Tomato Salad'), (SELECT id FROM ingredients WHERE name = 'Tomato'), 50, 'g'),
  ((SELECT id FROM recipes WHERE name = 'Cheese & Crackers'), (SELECT id FROM ingredients WHERE name = 'Cheddar Cheese'), 30, 'g'),
  ((SELECT id FROM recipes WHERE name = 'Cheese & Crackers'), (SELECT id FROM ingredients WHERE name = 'Whole Wheat Bread'), 2, 'slice'),
  ((SELECT id FROM recipes WHERE name = 'Banana & Almond Butter'), (SELECT id FROM ingredients WHERE name = 'Banana'), 1, 'piece'),
  ((SELECT id FROM recipes WHERE name = 'Banana & Almond Butter'), (SELECT id FROM ingredients WHERE name = 'Almonds'), 20, 'g'),
  ((SELECT id FROM recipes WHERE name = 'Spinach & Tofu Bites'), (SELECT id FROM ingredients WHERE name = 'Spinach'), 30, 'g'),
  ((SELECT id FROM recipes WHERE name = 'Spinach & Tofu Bites'), (SELECT id FROM ingredients WHERE name = 'Tofu'), 50, 'g'),
  -- Extra recipes start here
  ((SELECT id FROM recipes WHERE name = 'High-Protein Yogurt Bowl'), (SELECT id FROM ingredients WHERE name = 'Greek Yogurt'), 150, 'g'),
  ((SELECT id FROM recipes WHERE name = 'High-Protein Yogurt Bowl'), (SELECT id FROM ingredients WHERE name = 'Oats'), 30, 'g'),
  ((SELECT id FROM recipes WHERE name = 'High-Protein Yogurt Bowl'), (SELECT id FROM ingredients WHERE name = 'Almonds'), 15, 'g'),
  ((SELECT id FROM recipes WHERE name = 'Veggie Omelette Toast'), (SELECT id FROM ingredients WHERE name = 'Egg'), 2, 'piece'),
  ((SELECT id FROM recipes WHERE name = 'Veggie Omelette Toast'), (SELECT id FROM ingredients WHERE name = 'Spinach'), 30, 'g'),
  ((SELECT id FROM recipes WHERE name = 'Veggie Omelette Toast'), (SELECT id FROM ingredients WHERE name = 'Tomato'), 30, 'g'),
  ((SELECT id FROM recipes WHERE name = 'Veggie Omelette Toast'), (SELECT id FROM ingredients WHERE name = 'Whole Wheat Bread'), 1, 'slice'),
  ((SELECT id FROM recipes WHERE name = 'Tofu Breakfast Bowl'), (SELECT id FROM ingredients WHERE name = 'Tofu'), 100, 'g'),
  ((SELECT id FROM recipes WHERE name = 'Tofu Breakfast Bowl'), (SELECT id FROM ingredients WHERE name = 'Oats'), 30, 'g'),
  ((SELECT id FROM recipes WHERE name = 'Tofu Breakfast Bowl'), (SELECT id FROM ingredients WHERE name = 'Banana'), 1, 'piece'),
  ((SELECT id FROM recipes WHERE name = 'Tofu Breakfast Bowl'), (SELECT id FROM ingredients WHERE name = 'Spinach'), 30, 'g'),
  ((SELECT id FROM recipes WHERE name = 'Peanut Butter Banana Oats'), (SELECT id FROM ingredients WHERE name = 'Oats'), 50, 'g'),
  ((SELECT id FROM recipes WHERE name = 'Peanut Butter Banana Oats'), (SELECT id FROM ingredients WHERE name = 'Banana'), 1, 'piece'),
  ((SELECT id FROM recipes WHERE name = 'Peanut Butter Banana Oats'), (SELECT id FROM ingredients WHERE name = 'Peanut Butter'), 15, 'g'),
  ((SELECT id FROM recipes WHERE name = 'Chicken Lentil Power Bowl'), (SELECT id FROM ingredients WHERE name = 'Chicken Breast'), 100, 'g'),
  ((SELECT id FROM recipes WHERE name = 'Chicken Lentil Power Bowl'), (SELECT id FROM ingredients WHERE name = 'Lentils'), 80, 'g'),
  ((SELECT id FROM recipes WHERE name = 'Chicken Lentil Power Bowl'), (SELECT id FROM ingredients WHERE name = 'Spinach'), 30, 'g'),
  ((SELECT id FROM recipes WHERE name = 'Chicken Lentil Power Bowl'), (SELECT id FROM ingredients WHERE name = 'Tomato'), 30, 'g'),
  ((SELECT id FROM recipes WHERE name = 'Spiced Chickpea Rice Bowl'), (SELECT id FROM ingredients WHERE name = 'Chickpeas'), 100, 'g'),
  ((SELECT id FROM recipes WHERE name = 'Spiced Chickpea Rice Bowl'), (SELECT id FROM ingredients WHERE name = 'Rice'), 80, 'g'),
  ((SELECT id FROM recipes WHERE name = 'Spiced Chickpea Rice Bowl'), (SELECT id FROM ingredients WHERE name = 'Tomato'), 30, 'g'),
  ((SELECT id FROM recipes WHERE name = 'Spiced Chickpea Rice Bowl'), (SELECT id FROM ingredients WHERE name = 'Cucumber'), 30, 'g'),
  ((SELECT id FROM recipes WHERE name = 'Salmon Lentil Salad'), (SELECT id FROM ingredients WHERE name = 'Salmon'), 80, 'g'),
  ((SELECT id FROM recipes WHERE name = 'Salmon Lentil Salad'), (SELECT id FROM ingredients WHERE name = 'Lentils'), 60, 'g'),
  ((SELECT id FROM recipes WHERE name = 'Salmon Lentil Salad'), (SELECT id FROM ingredients WHERE name = 'Spinach'), 30, 'g'),
  ((SELECT id FROM recipes WHERE name = 'Salmon Lentil Salad'), (SELECT id FROM ingredients WHERE name = 'Tomato'), 30, 'g'),
  ((SELECT id FROM recipes WHERE name = 'Tofu Chickpea Stir Fry'), (SELECT id FROM ingredients WHERE name = 'Tofu'), 80, 'g'),
  ((SELECT id FROM recipes WHERE name = 'Tofu Chickpea Stir Fry'), (SELECT id FROM ingredients WHERE name = 'Chickpeas'), 60, 'g'),
  ((SELECT id FROM recipes WHERE name = 'Tofu Chickpea Stir Fry'), (SELECT id FROM ingredients WHERE name = 'Broccoli'), 50, 'g'),
  ((SELECT id FROM recipes WHERE name = 'Tofu Chickpea Stir Fry'), (SELECT id FROM ingredients WHERE name = 'Tomato'), 30, 'g'),
  ((SELECT id FROM recipes WHERE name = 'Chicken Veggie Skillet'), (SELECT id FROM ingredients WHERE name = 'Chicken Breast'), 120, 'g'),
  ((SELECT id FROM recipes WHERE name = 'Chicken Veggie Skillet'), (SELECT id FROM ingredients WHERE name = 'Broccoli'), 80, 'g'),
  ((SELECT id FROM recipes WHERE name = 'Chicken Veggie Skillet'), (SELECT id FROM ingredients WHERE name = 'Tomato'), 40, 'g'),
  ((SELECT id FROM recipes WHERE name = 'Chicken Veggie Skillet'), (SELECT id FROM ingredients WHERE name = 'Spinach'), 30, 'g'),
  ((SELECT id FROM recipes WHERE name = 'Low-Carb Chicken & Avocado Plate'), (SELECT id FROM ingredients WHERE name = 'Chicken Breast'), 120, 'g'),
  ((SELECT id FROM recipes WHERE name = 'Low-Carb Chicken & Avocado Plate'), (SELECT id FROM ingredients WHERE name = 'Avocado'), 0.5, 'piece'),
  ((SELECT id FROM recipes WHERE name = 'Low-Carb Chicken & Avocado Plate'), (SELECT id FROM ingredients WHERE name = 'Spinach'), 40, 'g'),
  ((SELECT id FROM recipes WHERE name = 'Lentil & Chickpea Curry Bowl'), (SELECT id FROM ingredients WHERE name = 'Lentils'), 80, 'g'),
  ((SELECT id FROM recipes WHERE name = 'Lentil & Chickpea Curry Bowl'), (SELECT id FROM ingredients WHERE name = 'Chickpeas'), 70, 'g'),
  ((SELECT id FROM recipes WHERE name = 'Lentil & Chickpea Curry Bowl'), (SELECT id FROM ingredients WHERE name = 'Tomato'), 40, 'g'),
  ((SELECT id FROM recipes WHERE name = 'Lentil & Chickpea Curry Bowl'), (SELECT id FROM ingredients WHERE name = 'Spinach'), 30, 'g'),
  ((SELECT id FROM recipes WHERE name = 'Tofu Rice Bowl'), (SELECT id FROM ingredients WHERE name = 'Tofu'), 100, 'g'),
  ((SELECT id FROM recipes WHERE name = 'Tofu Rice Bowl'), (SELECT id FROM ingredients WHERE name = 'Rice'), 80, 'g'),
  ((SELECT id FROM recipes WHERE name = 'Tofu Rice Bowl'), (SELECT id FROM ingredients WHERE name = 'Spinach'), 40, 'g'),
  ((SELECT id FROM recipes WHERE name = 'Tofu Rice Bowl'), (SELECT id FROM ingredients WHERE name = 'Broccoli'), 50, 'g'),
  ((SELECT id FROM recipes WHERE name = 'Protein Yogurt Parfait'), (SELECT id FROM ingredients WHERE name = 'Greek Yogurt'), 80, 'g'),
  ((SELECT id FROM recipes WHERE name = 'Protein Yogurt Parfait'), (SELECT id FROM ingredients WHERE name = 'Oats'), 20, 'g'),
  ((SELECT id FROM recipes WHERE name = 'Protein Yogurt Parfait'), (SELECT id FROM ingredients WHERE name = 'Banana'), 1, 'piece'),
  ((SELECT id FROM recipes WHERE name = 'Protein Yogurt Parfait'), (SELECT id FROM ingredients WHERE name = 'Almonds'), 10, 'g'),
  ((SELECT id FROM recipes WHERE name = 'Chickpea Crunch Cup'), (SELECT id FROM ingredients WHERE name = 'Chickpeas'), 60, 'g'),
  ((SELECT id FROM recipes WHERE name = 'Chickpea Crunch Cup'), (SELECT id FROM ingredients WHERE name = 'Tomato'), 30, 'g'),
  ((SELECT id FROM recipes WHERE name = 'Chickpea Crunch Cup'), (SELECT id FROM ingredients WHERE name = 'Cucumber'), 30, 'g'),
  ((SELECT id FROM recipes WHERE name = 'Egg & Cucumber Bites'), (SELECT id FROM ingredients WHERE name = 'Egg'), 1, 'piece'),
  ((SELECT id FROM recipes WHERE name = 'Egg & Cucumber Bites'), (SELECT id FROM ingredients WHERE name = 'Cucumber'), 40, 'g'),
  ((SELECT id FROM recipes WHERE name = 'Apple Peanut Oat Bites'), (SELECT id FROM ingredients WHERE name = 'Apple'), 1, 'piece'),
  ((SELECT id FROM recipes WHERE name = 'Apple Peanut Oat Bites'), (SELECT id FROM ingredients WHERE name = 'Peanut Butter'), 15, 'g'),
  ((SELECT id FROM recipes WHERE name = 'Apple Peanut Oat Bites'), (SELECT id FROM ingredients WHERE name = 'Oats'), 15, 'g'),
  -- Drinkable recipes
  ((SELECT id FROM recipes WHERE name = 'Banana Oat Protein Shake'), (SELECT id FROM ingredients WHERE name = 'Banana'), 1, 'piece'),
  ((SELECT id FROM recipes WHERE name = 'Banana Oat Protein Shake'), (SELECT id FROM ingredients WHERE name = 'Oats'), 40, 'g'),
  ((SELECT id FROM recipes WHERE name = 'Banana Oat Protein Shake'), (SELECT id FROM ingredients WHERE name = 'Peanut Butter'), 15, 'g'),
  ((SELECT id FROM recipes WHERE name = 'Banana Oat Protein Shake'), (SELECT id FROM ingredients WHERE name = 'Greek Yogurt'), 100, 'g'),
  ((SELECT id FROM recipes WHERE name = 'Green Yogurt Smoothie'), (SELECT id FROM ingredients WHERE name = 'Greek Yogurt'), 120, 'g'),
  ((SELECT id FROM recipes WHERE name = 'Green Yogurt Smoothie'), (SELECT id FROM ingredients WHERE name = 'Spinach'), 40, 'g'),
  ((SELECT id FROM recipes WHERE name = 'Green Yogurt Smoothie'), (SELECT id FROM ingredients WHERE name = 'Banana'), 1, 'piece'),
  ((SELECT id FROM recipes WHERE name = 'Peanut Butter Oat Smoothie'), (SELECT id FROM ingredients WHERE name = 'Oats'), 50, 'g'),
  ((SELECT id FROM recipes WHERE name = 'Peanut Butter Oat Smoothie'), (SELECT id FROM ingredients WHERE name = 'Peanut Butter'), 20, 'g'),
  ((SELECT id FROM recipes WHERE name = 'Peanut Butter Oat Smoothie'), (SELECT id FROM ingredients WHERE name = 'Greek Yogurt'), 80, 'g'),
  ((SELECT id FROM recipes WHERE name = 'Peanut Butter Oat Smoothie'), (SELECT id FROM ingredients WHERE name = 'Banana'), 1, 'piece');
