export interface IngredientSeed {
  name: string;
  brand?: string;
  unit: 'per_100g' | 'per_piece' | 'per_serving' | 'per_ml';
  kcalPerUnit: number;
  proteinPerUnit: number;
  carbsPerUnit: number;
  fatPerUnit: number;
  estimatedPricePerUnit: number;
  tags: string[];
}

export interface RecipeIngredientSeed {
  ingredientName: string;
  quantity: number;
  quantityUnit: string;
}

export interface RecipeSeed {
  name: string;
  mealSlot: 'breakfast' | 'snack' | 'lunch' | 'dinner';
  difficulty: 'super_easy' | 'easy' | 'medium' | 'hard';
  description?: string;
  baseKcal: number;
  baseProtein: number;
  baseCarbs: number;
  baseFat: number;
  baseEstimatedCost: number;
  ingredients: RecipeIngredientSeed[];
}

export const mockIngredients: IngredientSeed[] = [
  {
    name: 'Tesco Free-Range Eggs',
    unit: 'per_piece',
    kcalPerUnit: 68,
    proteinPerUnit: 6,
    carbsPerUnit: 0.6,
    fatPerUnit: 4.8,
    estimatedPricePerUnit: 0.22,
    tags: ['halal', 'vegetarian'],
  },
  {
    name: 'Aldi Whole Milk',
    unit: 'per_100g',
    kcalPerUnit: 64,
    proteinPerUnit: 3.3,
    carbsPerUnit: 4.8,
    fatPerUnit: 3.6,
    estimatedPricePerUnit: 0.07,
    tags: ['halal'],
  },
  {
    name: 'Alpro Oat Milk',
    unit: 'per_100g',
    kcalPerUnit: 46,
    proteinPerUnit: 1,
    carbsPerUnit: 7,
    fatPerUnit: 1.5,
    estimatedPricePerUnit: 0.14,
    tags: ['vegan'],
  },
  {
    name: 'Tesco Greek Yogurt 0% Fat',
    unit: 'per_100g',
    kcalPerUnit: 59,
    proteinPerUnit: 10,
    carbsPerUnit: 3.6,
    fatPerUnit: 0.4,
    estimatedPricePerUnit: 0.45,
    tags: ['vegetarian', 'halal'],
  },
  {
    name: 'Sainsbury British Chicken Breast',
    unit: 'per_100g',
    kcalPerUnit: 110,
    proteinPerUnit: 23,
    carbsPerUnit: 0,
    fatPerUnit: 1.5,
    estimatedPricePerUnit: 0.95,
    tags: ['halal'],
  },
  {
    name: 'Quorn Vegan Pieces',
    unit: 'per_100g',
    kcalPerUnit: 98,
    proteinPerUnit: 14,
    carbsPerUnit: 3.2,
    fatPerUnit: 2,
    estimatedPricePerUnit: 1.1,
    tags: ['vegan'],
  },
  {
    name: 'Tesco Brown Rice',
    unit: 'per_100g',
    kcalPerUnit: 360,
    proteinPerUnit: 7.5,
    carbsPerUnit: 76,
    fatPerUnit: 2.7,
    estimatedPricePerUnit: 0.18,
    tags: ['vegan', 'gluten-free'],
  },
  {
    name: 'Merchant Gourmet Puy Lentils',
    unit: 'per_100g',
    kcalPerUnit: 116,
    proteinPerUnit: 9,
    carbsPerUnit: 17,
    fatPerUnit: 0.6,
    estimatedPricePerUnit: 0.65,
    tags: ['vegan', 'halal', 'gluten-free'],
  },
  {
    name: 'Tesco Sweet Potato',
    unit: 'per_100g',
    kcalPerUnit: 86,
    proteinPerUnit: 1.6,
    carbsPerUnit: 20,
    fatPerUnit: 0.1,
    estimatedPricePerUnit: 0.32,
    tags: ['vegan', 'halal', 'gluten-free'],
  },
  {
    name: 'Essential Waitrose Spinach',
    unit: 'per_100g',
    kcalPerUnit: 23,
    proteinPerUnit: 2.9,
    carbsPerUnit: 1.9,
    fatPerUnit: 0.4,
    estimatedPricePerUnit: 0.6,
    tags: ['vegan', 'halal', 'gluten-free'],
  },
  {
    name: 'Tesco Cherry Tomatoes',
    unit: 'per_100g',
    kcalPerUnit: 18,
    proteinPerUnit: 0.9,
    carbsPerUnit: 3.9,
    fatPerUnit: 0.2,
    estimatedPricePerUnit: 0.4,
    tags: ['vegan', 'halal', 'gluten-free'],
  },
  {
    name: 'Sainsbury Smoked Salmon',
    unit: 'per_100g',
    kcalPerUnit: 178,
    proteinPerUnit: 22,
    carbsPerUnit: 0,
    fatPerUnit: 10,
    estimatedPricePerUnit: 2.5,
    tags: ['halal?'],
  },
  {
    name: 'Tesco Wholemeal Bread',
    unit: 'per_piece',
    kcalPerUnit: 85,
    proteinPerUnit: 3.6,
    carbsPerUnit: 15,
    fatPerUnit: 1.1,
    estimatedPricePerUnit: 0.12,
    tags: ['vegan'],
  },
  {
    name: 'Warburtons Gluten Free Wrap',
    unit: 'per_piece',
    kcalPerUnit: 158,
    proteinPerUnit: 2.7,
    carbsPerUnit: 33,
    fatPerUnit: 2.8,
    estimatedPricePerUnit: 0.85,
    tags: ['vegan', 'gluten-free'],
  },
  {
    name: 'Tesco Avocado',
    unit: 'per_piece',
    kcalPerUnit: 250,
    proteinPerUnit: 3,
    carbsPerUnit: 12,
    fatPerUnit: 22,
    estimatedPricePerUnit: 0.95,
    tags: ['vegan', 'halal'],
  },
  {
    name: 'Alpro Plain Yogurt',
    unit: 'per_100g',
    kcalPerUnit: 54,
    proteinPerUnit: 3.9,
    carbsPerUnit: 2.5,
    fatPerUnit: 2.2,
    estimatedPricePerUnit: 0.55,
    tags: ['vegan'],
  },
  {
    name: 'Heinz Baked Beans',
    unit: 'per_100g',
    kcalPerUnit: 78,
    proteinPerUnit: 4.7,
    carbsPerUnit: 14,
    fatPerUnit: 0.2,
    estimatedPricePerUnit: 0.25,
    tags: ['vegan', 'halal'],
  },
  {
    name: 'Linda McCartney Sausages',
    unit: 'per_piece',
    kcalPerUnit: 110,
    proteinPerUnit: 11,
    carbsPerUnit: 4,
    fatPerUnit: 4,
    estimatedPricePerUnit: 0.6,
    tags: ['vegan'],
  },
  {
    name: 'Tesco Extra Mature Cheddar',
    unit: 'per_100g',
    kcalPerUnit: 416,
    proteinPerUnit: 25,
    carbsPerUnit: 1.2,
    fatPerUnit: 35,
    estimatedPricePerUnit: 1.1,
    tags: ['vegetarian'],
  },
  {
    name: 'Cauldron Organic Tofu',
    unit: 'per_100g',
    kcalPerUnit: 124,
    proteinPerUnit: 12,
    carbsPerUnit: 3,
    fatPerUnit: 7,
    estimatedPricePerUnit: 0.85,
    tags: ['vegan'],
  },
  {
    name: 'Tesco Salmon Fillets',
    unit: 'per_100g',
    kcalPerUnit: 208,
    proteinPerUnit: 20,
    carbsPerUnit: 0,
    fatPerUnit: 14,
    estimatedPricePerUnit: 1.6,
    tags: ['halal'],
  },
  {
    name: 'Merchant Gourmet Giant Couscous',
    unit: 'per_100g',
    kcalPerUnit: 360,
    proteinPerUnit: 13,
    carbsPerUnit: 73,
    fatPerUnit: 1.8,
    estimatedPricePerUnit: 0.4,
    tags: ['vegan'],
  },
  {
    name: 'Tesco Chickpeas',
    unit: 'per_100g',
    kcalPerUnit: 164,
    proteinPerUnit: 9,
    carbsPerUnit: 27,
    fatPerUnit: 3,
    estimatedPricePerUnit: 0.2,
    tags: ['vegan', 'halal', 'gluten-free'],
  },
  {
    name: 'Aldi Peanut Butter',
    unit: 'per_100g',
    kcalPerUnit: 588,
    proteinPerUnit: 25,
    carbsPerUnit: 14,
    fatPerUnit: 50,
    estimatedPricePerUnit: 0.85,
    tags: ['vegan', 'halal'],
  },
  {
    name: 'Tesco Porridge Oats',
    unit: 'per_100g',
    kcalPerUnit: 370,
    proteinPerUnit: 11,
    carbsPerUnit: 60,
    fatPerUnit: 8,
    estimatedPricePerUnit: 0.2,
    tags: ['vegan'],
  },
  {
    name: 'Blueberries',
    unit: 'per_100g',
    kcalPerUnit: 57,
    proteinPerUnit: 0.7,
    carbsPerUnit: 14,
    fatPerUnit: 0.3,
    estimatedPricePerUnit: 0.9,
    tags: ['vegan', 'halal', 'gluten-free'],
  },
  {
    name: 'Banana',
    unit: 'per_piece',
    kcalPerUnit: 105,
    proteinPerUnit: 1.3,
    carbsPerUnit: 27,
    fatPerUnit: 0.3,
    estimatedPricePerUnit: 0.18,
    tags: ['vegan', 'halal'],
  },
  {
    name: 'Ryelands Turkey Mince 5% Fat',
    unit: 'per_100g',
    kcalPerUnit: 135,
    proteinPerUnit: 20,
    carbsPerUnit: 0,
    fatPerUnit: 5,
    estimatedPricePerUnit: 1.0,
    tags: ['halal'],
  },
  {
    name: 'Tesco Courgette',
    unit: 'per_100g',
    kcalPerUnit: 17,
    proteinPerUnit: 1.2,
    carbsPerUnit: 3.1,
    fatPerUnit: 0.3,
    estimatedPricePerUnit: 0.3,
    tags: ['vegan', 'halal', 'gluten-free'],
  },
  {
    name: 'Red Onion',
    unit: 'per_100g',
    kcalPerUnit: 40,
    proteinPerUnit: 1.1,
    carbsPerUnit: 9,
    fatPerUnit: 0.1,
    estimatedPricePerUnit: 0.25,
    tags: ['vegan', 'halal', 'gluten-free'],
  },
  {
    name: 'Garlic Clove',
    unit: 'per_piece',
    kcalPerUnit: 4,
    proteinPerUnit: 0.2,
    carbsPerUnit: 1,
    fatPerUnit: 0,
    estimatedPricePerUnit: 0.05,
    tags: ['vegan', 'halal', 'gluten-free'],
  },
  {
    name: 'Olive Oil',
    unit: 'per_100g',
    kcalPerUnit: 884,
    proteinPerUnit: 0,
    carbsPerUnit: 0,
    fatPerUnit: 100,
    estimatedPricePerUnit: 1.2,
    tags: ['vegan', 'halal', 'keto'],
  },
  {
    name: 'Baby Leaf Salad',
    unit: 'per_100g',
    kcalPerUnit: 20,
    proteinPerUnit: 2,
    carbsPerUnit: 1.5,
    fatPerUnit: 0.3,
    estimatedPricePerUnit: 0.65,
    tags: ['vegan', 'halal', 'gluten-free'],
  },
  {
    name: 'Tesco Couscous',
    unit: 'per_100g',
    kcalPerUnit: 360,
    proteinPerUnit: 13,
    carbsPerUnit: 74,
    fatPerUnit: 1.5,
    estimatedPricePerUnit: 0.16,
    tags: ['vegan'],
  },
  {
    name: 'Red Lentil Pasta',
    unit: 'per_100g',
    kcalPerUnit: 340,
    proteinPerUnit: 24,
    carbsPerUnit: 56,
    fatPerUnit: 2,
    estimatedPricePerUnit: 0.45,
    tags: ['vegan', 'gluten-free'],
  },
  {
    name: 'Tesco Chopped Tomatoes',
    unit: 'per_100g',
    kcalPerUnit: 32,
    proteinPerUnit: 1.5,
    carbsPerUnit: 7,
    fatPerUnit: 0.3,
    estimatedPricePerUnit: 0.15,
    tags: ['vegan', 'halal', 'gluten-free'],
  },
  {
    name: 'Coconut Milk Light',
    unit: 'per_100g',
    kcalPerUnit: 154,
    proteinPerUnit: 1.5,
    carbsPerUnit: 3,
    fatPerUnit: 15,
    estimatedPricePerUnit: 0.5,
    tags: ['vegan', 'halal'],
  },
  {
    name: 'Tesco Frozen Peas',
    unit: 'per_100g',
    kcalPerUnit: 68,
    proteinPerUnit: 5,
    carbsPerUnit: 12,
    fatPerUnit: 0.5,
    estimatedPricePerUnit: 0.18,
    tags: ['vegan', 'halal', 'gluten-free'],
  },
  {
    name: 'Chia Seeds',
    unit: 'per_100g',
    kcalPerUnit: 486,
    proteinPerUnit: 17,
    carbsPerUnit: 42,
    fatPerUnit: 31,
    estimatedPricePerUnit: 1.1,
    tags: ['vegan', 'keto'],
  },
  {
    name: 'Pumpkin Seeds',
    unit: 'per_100g',
    kcalPerUnit: 559,
    proteinPerUnit: 30,
    carbsPerUnit: 11,
    fatPerUnit: 49,
    estimatedPricePerUnit: 1.2,
    tags: ['vegan', 'keto'],
  },
  {
    name: 'Tesco Falafel',
    unit: 'per_piece',
    kcalPerUnit: 52,
    proteinPerUnit: 2,
    carbsPerUnit: 5,
    fatPerUnit: 3,
    estimatedPricePerUnit: 0.35,
    tags: ['vegan'],
  },
  {
    name: 'Aldi Halloumi',
    unit: 'per_100g',
    kcalPerUnit: 316,
    proteinPerUnit: 22,
    carbsPerUnit: 2,
    fatPerUnit: 25,
    estimatedPricePerUnit: 1.2,
    tags: ['vegetarian'],
  },
  {
    name: 'Tesco Wholewheat Penne',
    unit: 'per_100g',
    kcalPerUnit: 350,
    proteinPerUnit: 13,
    carbsPerUnit: 70,
    fatPerUnit: 2,
    estimatedPricePerUnit: 0.2,
    tags: ['vegan'],
  },
  {
    name: 'Tesco Passata',
    unit: 'per_100g',
    kcalPerUnit: 33,
    proteinPerUnit: 1.8,
    carbsPerUnit: 7,
    fatPerUnit: 0.2,
    estimatedPricePerUnit: 0.18,
    tags: ['vegan', 'halal', 'gluten-free'],
  },
  {
    name: 'Aldi Greek Style Flatbread',
    unit: 'per_piece',
    kcalPerUnit: 170,
    proteinPerUnit: 5,
    carbsPerUnit: 28,
    fatPerUnit: 4,
    estimatedPricePerUnit: 0.35,
    tags: ['vegetarian'],
  },
  {
    name: 'Tesco Crunchy Lettuce',
    unit: 'per_100g',
    kcalPerUnit: 16,
    proteinPerUnit: 1,
    carbsPerUnit: 3,
    fatPerUnit: 0.2,
    estimatedPricePerUnit: 0.25,
    tags: ['vegan', 'gluten-free'],
  }
];

export const mockRecipes: RecipeSeed[] = [
  {
    name: 'Smoked Salmon Bagel',
    mealSlot: 'breakfast',
    difficulty: 'easy',
    description: 'Wholemeal bagel with cream cheese, smoked salmon and greens.',
    baseKcal: 420,
    baseProtein: 24,
    baseCarbs: 45,
    baseFat: 16,
    baseEstimatedCost: 3.3,
    ingredients: [
      { ingredientName: 'Tesco Wholemeal Bread', quantity: 2, quantityUnit: 'slice' },
      { ingredientName: 'Sainsbury Smoked Salmon', quantity: 80, quantityUnit: 'g' },
      { ingredientName: 'Tesco Greek Yogurt 0% Fat', quantity: 50, quantityUnit: 'g' },
      { ingredientName: 'Baby Leaf Salad', quantity: 30, quantityUnit: 'g' }
    ],
  },
  {
    name: 'Protein Overnight Oats',
    mealSlot: 'breakfast',
    difficulty: 'super_easy',
    baseKcal: 380,
    baseProtein: 25,
    baseCarbs: 45,
    baseFat: 11,
    baseEstimatedCost: 1.2,
    ingredients: [
      { ingredientName: 'Tesco Porridge Oats', quantity: 60, quantityUnit: 'g' },
      { ingredientName: 'Alpro Oat Milk', quantity: 200, quantityUnit: 'ml' },
      { ingredientName: 'Chia Seeds', quantity: 15, quantityUnit: 'g' },
      { ingredientName: 'Blueberries', quantity: 60, quantityUnit: 'g' }
    ],
  },
  {
    name: 'Veggie Full English',
    mealSlot: 'breakfast',
    difficulty: 'medium',
    baseKcal: 520,
    baseProtein: 28,
    baseCarbs: 45,
    baseFat: 22,
    baseEstimatedCost: 2.8,
    ingredients: [
      { ingredientName: 'Linda McCartney Sausages', quantity: 2, quantityUnit: 'piece' },
      { ingredientName: 'Tesco Free-Range Eggs', quantity: 2, quantityUnit: 'piece' },
      { ingredientName: 'Heinz Baked Beans', quantity: 150, quantityUnit: 'g' },
      { ingredientName: 'Tesco Cherry Tomatoes', quantity: 80, quantityUnit: 'g' }
    ],
  },
  {
    name: 'Halloumi Couscous Bowl',
    mealSlot: 'lunch',
    difficulty: 'easy',
    baseKcal: 650,
    baseProtein: 28,
    baseCarbs: 70,
    baseFat: 24,
    baseEstimatedCost: 3,
    ingredients: [
      { ingredientName: 'Aldi Halloumi', quantity: 80, quantityUnit: 'g' },
      { ingredientName: 'Merchant Gourmet Giant Couscous', quantity: 80, quantityUnit: 'g' },
      { ingredientName: 'Tesco Cherry Tomatoes', quantity: 60, quantityUnit: 'g' },
      { ingredientName: 'Baby Leaf Salad', quantity: 60, quantityUnit: 'g' }
    ],
  },
  {
    name: 'Chicken & Sweet Potato Traybake',
    mealSlot: 'dinner',
    difficulty: 'easy',
    baseKcal: 580,
    baseProtein: 45,
    baseCarbs: 55,
    baseFat: 18,
    baseEstimatedCost: 3.5,
    ingredients: [
      { ingredientName: 'Sainsbury British Chicken Breast', quantity: 180, quantityUnit: 'g' },
      { ingredientName: 'Tesco Sweet Potato', quantity: 200, quantityUnit: 'g' },
      { ingredientName: 'Tesco Courgette', quantity: 120, quantityUnit: 'g' },
      { ingredientName: 'Olive Oil', quantity: 10, quantityUnit: 'g' }
    ],
  },
  {
    name: 'Tofu Stir Fry',
    mealSlot: 'dinner',
    difficulty: 'easy',
    baseKcal: 520,
    baseProtein: 32,
    baseCarbs: 55,
    baseFat: 18,
    baseEstimatedCost: 2.7,
    ingredients: [
      { ingredientName: 'Cauldron Organic Tofu', quantity: 150, quantityUnit: 'g' },
      { ingredientName: 'Tesco Brown Rice', quantity: 70, quantityUnit: 'g' },
      { ingredientName: 'Essential Waitrose Spinach', quantity: 60, quantityUnit: 'g' },
      { ingredientName: 'Red Onion', quantity: 60, quantityUnit: 'g' }
    ],
  },
  {
    name: 'Turkey Ragu with Lentil Pasta',
    mealSlot: 'dinner',
    difficulty: 'medium',
    baseKcal: 640,
    baseProtein: 45,
    baseCarbs: 60,
    baseFat: 18,
    baseEstimatedCost: 3.1,
    ingredients: [
      { ingredientName: 'Ryelands Turkey Mince 5% Fat', quantity: 180, quantityUnit: 'g' },
      { ingredientName: 'Red Lentil Pasta', quantity: 80, quantityUnit: 'g' },
      { ingredientName: 'Tesco Chopped Tomatoes', quantity: 200, quantityUnit: 'g' },
      { ingredientName: 'Garlic Clove', quantity: 2, quantityUnit: 'piece' }
    ],
  },
  {
    name: 'Chickpea Buddha Bowl',
    mealSlot: 'lunch',
    difficulty: 'easy',
    baseKcal: 520,
    baseProtein: 22,
    baseCarbs: 70,
    baseFat: 16,
    baseEstimatedCost: 2,
    ingredients: [
      { ingredientName: 'Tesco Chickpeas', quantity: 160, quantityUnit: 'g' },
      { ingredientName: 'Tesco Brown Rice', quantity: 60, quantityUnit: 'g' },
      { ingredientName: 'Tesco Avocado', quantity: 0.5, quantityUnit: 'piece' },
      { ingredientName: 'Baby Leaf Salad', quantity: 50, quantityUnit: 'g' }
    ],
  },
  {
    name: 'Mediterranean Couscous Salad',
    mealSlot: 'lunch',
    difficulty: 'super_easy',
    baseKcal: 480,
    baseProtein: 18,
    baseCarbs: 65,
    baseFat: 14,
    baseEstimatedCost: 1.8,
    ingredients: [
      { ingredientName: 'Tesco Couscous', quantity: 70, quantityUnit: 'g' },
      { ingredientName: 'Tesco Cherry Tomatoes', quantity: 80, quantityUnit: 'g' },
      { ingredientName: 'Tesco Crunchy Lettuce', quantity: 60, quantityUnit: 'g' },
      { ingredientName: 'Tesco Falafel', quantity: 3, quantityUnit: 'piece' }
    ],
  },
  {
    name: 'Protein Berry Smoothie',
    mealSlot: 'snack',
    difficulty: 'super_easy',
    baseKcal: 250,
    baseProtein: 18,
    baseCarbs: 32,
    baseFat: 6,
    baseEstimatedCost: 1.6,
    ingredients: [
      { ingredientName: 'Alpro Oat Milk', quantity: 200, quantityUnit: 'ml' },
      { ingredientName: 'Blueberries', quantity: 80, quantityUnit: 'g' },
      { ingredientName: 'Tesco Greek Yogurt 0% Fat', quantity: 80, quantityUnit: 'g' }
    ],
  },
  {
    name: 'Peanut Butter Banana Toast',
    mealSlot: 'snack',
    difficulty: 'super_easy',
    baseKcal: 290,
    baseProtein: 11,
    baseCarbs: 32,
    baseFat: 13,
    baseEstimatedCost: 0.9,
    ingredients: [
      { ingredientName: 'Tesco Wholemeal Bread', quantity: 1, quantityUnit: 'slice' },
      { ingredientName: 'Aldi Peanut Butter', quantity: 20, quantityUnit: 'g' },
      { ingredientName: 'Banana', quantity: 0.5, quantityUnit: 'piece' }
    ],
  },
  {
    name: 'Avocado Egg Wrap',
    mealSlot: 'lunch',
    difficulty: 'easy',
    baseKcal: 520,
    baseProtein: 24,
    baseCarbs: 45,
    baseFat: 28,
    baseEstimatedCost: 2.6,
    ingredients: [
      { ingredientName: 'Warburtons Gluten Free Wrap', quantity: 1, quantityUnit: 'piece' },
      { ingredientName: 'Tesco Avocado', quantity: 0.5, quantityUnit: 'piece' },
      { ingredientName: 'Tesco Free-Range Eggs', quantity: 2, quantityUnit: 'piece' },
      { ingredientName: 'Baby Leaf Salad', quantity: 40, quantityUnit: 'g' }
    ],
  },
  {
    name: 'Lentil Coconut Curry',
    mealSlot: 'dinner',
    difficulty: 'medium',
    baseKcal: 610,
    baseProtein: 26,
    baseCarbs: 70,
    baseFat: 22,
    baseEstimatedCost: 2.4,
    ingredients: [
      { ingredientName: 'Merchant Gourmet Puy Lentils', quantity: 160, quantityUnit: 'g' },
      { ingredientName: 'Tesco Chopped Tomatoes', quantity: 200, quantityUnit: 'g' },
      { ingredientName: 'Coconut Milk Light', quantity: 120, quantityUnit: 'g' },
      { ingredientName: 'Tesco Brown Rice', quantity: 60, quantityUnit: 'g' }
    ],
  },
  {
    name: 'Grilled Salmon & Greens',
    mealSlot: 'dinner',
    difficulty: 'easy',
    baseKcal: 540,
    baseProtein: 36,
    baseCarbs: 22,
    baseFat: 30,
    baseEstimatedCost: 4.2,
    ingredients: [
      { ingredientName: 'Tesco Salmon Fillets', quantity: 160, quantityUnit: 'g' },
      { ingredientName: 'Tesco Frozen Peas', quantity: 120, quantityUnit: 'g' },
      { ingredientName: 'Essential Waitrose Spinach', quantity: 60, quantityUnit: 'g' },
      { ingredientName: 'Olive Oil', quantity: 8, quantityUnit: 'g' }
    ],
  },
  {
    name: 'Tofu Buddha Bowl',
    mealSlot: 'dinner',
    difficulty: 'easy',
    baseKcal: 560,
    baseProtein: 30,
    baseCarbs: 65,
    baseFat: 18,
    baseEstimatedCost: 2.3,
    ingredients: [
      { ingredientName: 'Cauldron Organic Tofu', quantity: 150, quantityUnit: 'g' },
      { ingredientName: 'Tesco Brown Rice', quantity: 60, quantityUnit: 'g' },
      { ingredientName: 'Baby Leaf Salad', quantity: 60, quantityUnit: 'g' },
      { ingredientName: 'Tesco Cherry Tomatoes', quantity: 60, quantityUnit: 'g' }
    ],
  },
  {
    name: 'Falafel Flatbread',
    mealSlot: 'lunch',
    difficulty: 'easy',
    baseKcal: 540,
    baseProtein: 20,
    baseCarbs: 60,
    baseFat: 22,
    baseEstimatedCost: 2.4,
    ingredients: [
      { ingredientName: 'Aldi Greek Style Flatbread', quantity: 1, quantityUnit: 'piece' },
      { ingredientName: 'Tesco Falafel', quantity: 4, quantityUnit: 'piece' },
      { ingredientName: 'Tesco Greek Yogurt 0% Fat', quantity: 60, quantityUnit: 'g' },
      { ingredientName: 'Tesco Crunchy Lettuce', quantity: 50, quantityUnit: 'g' }
    ],
  },
  {
    name: 'Pea & Mint Soup',
    mealSlot: 'lunch',
    difficulty: 'easy',
    baseKcal: 320,
    baseProtein: 15,
    baseCarbs: 40,
    baseFat: 10,
    baseEstimatedCost: 1.6,
    ingredients: [
      { ingredientName: 'Tesco Frozen Peas', quantity: 200, quantityUnit: 'g' },
      { ingredientName: 'Tesco Greek Yogurt 0% Fat', quantity: 40, quantityUnit: 'g' },
      { ingredientName: 'Olive Oil', quantity: 5, quantityUnit: 'g' },
      { ingredientName: 'Garlic Clove', quantity: 1, quantityUnit: 'piece' }
    ],
  },
  {
    name: 'Salmon Pasta Salad',
    mealSlot: 'lunch',
    difficulty: 'easy',
    baseKcal: 620,
    baseProtein: 32,
    baseCarbs: 70,
    baseFat: 22,
    baseEstimatedCost: 3.8,
    ingredients: [
      { ingredientName: 'Tesco Salmon Fillets', quantity: 120, quantityUnit: 'g' },
      { ingredientName: 'Tesco Wholewheat Penne', quantity: 70, quantityUnit: 'g' },
      { ingredientName: 'Baby Leaf Salad', quantity: 50, quantityUnit: 'g' },
      { ingredientName: 'Tesco Cherry Tomatoes', quantity: 50, quantityUnit: 'g' }
    ],
  },
  {
    name: 'Protein Porridge Bowl',
    mealSlot: 'breakfast',
    difficulty: 'super_easy',
    baseKcal: 420,
    baseProtein: 22,
    baseCarbs: 55,
    baseFat: 13,
    baseEstimatedCost: 1.3,
    ingredients: [
      { ingredientName: 'Tesco Porridge Oats', quantity: 60, quantityUnit: 'g' },
      { ingredientName: 'Aldi Whole Milk', quantity: 200, quantityUnit: 'ml' },
      { ingredientName: 'Pumpkin Seeds', quantity: 15, quantityUnit: 'g' },
      { ingredientName: 'Banana', quantity: 0.5, quantityUnit: 'piece' }
    ],
  },
  {
    name: 'Light Chicken Salad',
    mealSlot: 'lunch',
    difficulty: 'easy',
    baseKcal: 420,
    baseProtein: 38,
    baseCarbs: 20,
    baseFat: 18,
    baseEstimatedCost: 2.9,
    ingredients: [
      { ingredientName: 'Sainsbury British Chicken Breast', quantity: 140, quantityUnit: 'g' },
      { ingredientName: 'Baby Leaf Salad', quantity: 60, quantityUnit: 'g' },
      { ingredientName: 'Tesco Cherry Tomatoes', quantity: 50, quantityUnit: 'g' },
      { ingredientName: 'Olive Oil', quantity: 6, quantityUnit: 'g' }
    ],
  },
  {
    name: 'Quorn Power Bowl',
    mealSlot: 'dinner',
    difficulty: 'easy',
    baseKcal: 530,
    baseProtein: 35,
    baseCarbs: 60,
    baseFat: 14,
    baseEstimatedCost: 2.5,
    ingredients: [
      { ingredientName: 'Quorn Vegan Pieces', quantity: 160, quantityUnit: 'g' },
      { ingredientName: 'Tesco Brown Rice', quantity: 60, quantityUnit: 'g' },
      { ingredientName: 'Tesco Frozen Peas', quantity: 60, quantityUnit: 'g' },
      { ingredientName: 'Essential Waitrose Spinach', quantity: 50, quantityUnit: 'g' }
    ],
  },
  {
    name: 'Spicy Chickpea Wrap',
    mealSlot: 'lunch',
    difficulty: 'easy',
    baseKcal: 560,
    baseProtein: 22,
    baseCarbs: 70,
    baseFat: 18,
    baseEstimatedCost: 2,
    ingredients: [
      { ingredientName: 'Warburtons Gluten Free Wrap', quantity: 1, quantityUnit: 'piece' },
      { ingredientName: 'Tesco Chickpeas', quantity: 140, quantityUnit: 'g' },
      { ingredientName: 'Tesco Crunchy Lettuce', quantity: 50, quantityUnit: 'g' },
      { ingredientName: 'Tesco Cherry Tomatoes', quantity: 40, quantityUnit: 'g' }
    ],
  },
  {
    name: 'Sweet Potato & Lentil Soup',
    mealSlot: 'dinner',
    difficulty: 'easy',
    baseKcal: 510,
    baseProtein: 20,
    baseCarbs: 75,
    baseFat: 12,
    baseEstimatedCost: 1.9,
    ingredients: [
      { ingredientName: 'Tesco Sweet Potato', quantity: 180, quantityUnit: 'g' },
      { ingredientName: 'Merchant Gourmet Puy Lentils', quantity: 140, quantityUnit: 'g' },
      { ingredientName: 'Tesco Chopped Tomatoes', quantity: 150, quantityUnit: 'g' },
      { ingredientName: 'Red Onion', quantity: 60, quantityUnit: 'g' }
    ],
  },
  {
    name: 'Greek Lentil Salad',
    mealSlot: 'lunch',
    difficulty: 'easy',
    baseKcal: 480,
    baseProtein: 24,
    baseCarbs: 55,
    baseFat: 16,
    baseEstimatedCost: 2.1,
    ingredients: [
      { ingredientName: 'Merchant Gourmet Puy Lentils', quantity: 140, quantityUnit: 'g' },
      { ingredientName: 'Tesco Cherry Tomatoes', quantity: 70, quantityUnit: 'g' },
      { ingredientName: 'Baby Leaf Salad', quantity: 60, quantityUnit: 'g' },
      { ingredientName: 'Tesco Greek Yogurt 0% Fat', quantity: 40, quantityUnit: 'g' }
    ],
  },
  {
    name: 'Protein Snack Box',
    mealSlot: 'snack',
    difficulty: 'super_easy',
    baseKcal: 230,
    baseProtein: 18,
    baseCarbs: 12,
    baseFat: 12,
    baseEstimatedCost: 1.4,
    ingredients: [
      { ingredientName: 'Tesco Free-Range Eggs', quantity: 1, quantityUnit: 'piece' },
      { ingredientName: 'Tesco Cherry Tomatoes', quantity: 60, quantityUnit: 'g' },
      { ingredientName: 'Pumpkin Seeds', quantity: 15, quantityUnit: 'g' }
    ],
  },
  {
    name: 'Coconut Chickpea Stew',
    mealSlot: 'dinner',
    difficulty: 'easy',
    baseKcal: 580,
    baseProtein: 23,
    baseCarbs: 70,
    baseFat: 20,
    baseEstimatedCost: 2.2,
    ingredients: [
      { ingredientName: 'Tesco Chickpeas', quantity: 160, quantityUnit: 'g' },
      { ingredientName: 'Coconut Milk Light', quantity: 120, quantityUnit: 'g' },
      { ingredientName: 'Tesco Chopped Tomatoes', quantity: 150, quantityUnit: 'g' },
      { ingredientName: 'Red Onion', quantity: 60, quantityUnit: 'g' }
    ],
  }
];
